data_pipeline:
 _target_: model_forge.data.datapipeline.PandasDataPipeline
 steps: 
  -
   _target_: forex_trader.ProcessData.data_cleaning.shift_close
   _partial_: true
  - 
    _target_: forex_trader.ProcessData.data_cleaning.create_label
    _partial_: true



Data_Source: 'data/Unprocessed_Data.csv'   


model:
  model_steps: 

  - select_features:
      _target_: forex_trader.Model.SklearnPipeline.FeatureSelector
      features: ['rsi'  , 'tv', 'sma', 'williams', 'regrs', 'cci', 'close_price', 'open_price', 'high_price', 'low_price' ]
      depth: 10
  
  - HistGradientBoostingClassifier:
      _target_: sklearn.ensemble.HistGradientBoostingClassifier
      learning_rate: 0.05723818391467435

      verbose: 0
      class_weight: balanced
      max_iter: 3997
      l2_regularization: 2.525756277489002
      early_stopping: True
      max_leaf_nodes: 106
      max_bins: 196
      max_depth: 605
      random_state: 42
