data_pipeline:
 _target_: model_forge.data.datapipeline.PandasDataPipeline
 steps: 
  -
   _target_: forex_trader.ProcessData.data_cleaning.shift_close
   _partial_: true
  - 
    _target_: forex_trader.ProcessData.data_cleaning.create_label
    _partial_: true
  -
    _target_: forex_trader.ProcessData.splits.train_test.add_train_test_indixes
    _partial_: true



Data_Source: 'data/Unprocessed_Data.csv'   


model:
  model_steps: 

  - select_features:
      _target_: forex_trader.Model.SklearnPipeline.FeatureSelector
      features: ['rsi'  , 'tv', 'sma', 'williams', 'regrs', 'cci', 'close_price', 'open_price', 'high_price', 'low_price' ]
      depth: 2

  - deeplearn:
      _target_: forex_trader.Model.deeplearn.neuralnet
      nodes:      ['10', '0.05',   '5', '2', '1']
      activation: ['relu', 'None',    'relu', 'softmax', 'sigmoid']
      layer_type: ['dense', 'dropout', ' dense',  'dense' , 'dense']
      epochs: 10000
