site_name: Forex Trading
nav:
  - Home: home.md
  - Indicators: indicators.md
  - API: index.md
theme: readthedocs
plugins:
  - search
  - swagger-ui-tag
  - mkdocstrings:
      default_handler: python
hooks:
  - deploy/scoring_script.py