data_pipeline:
 _target_: ProcessData.data_pipeline.PandasDataPipeline
 steps: 
  -
   _target_: ProcessData.data_cleaning.shift_close
   _partial_: true
  - 
    _target_: ProcessData.data_cleaning.create_label
    _partial_: true
  - 
    _target_: ProcessData.data_cleaning.drop_empty_window
    _partial_: true



Data_Source: './data/Unprocessed_Data.csv'   
  
model:
  model_params:
    learning_rate: 0.1
    max_depth: 15
    min_samples_leaf: 5
    max_leaf_nodes: 60
    l2_regularization: 1
    max_bins: 250
    max_iter: 25
    random_state: 2
  feature_depth: 1