data_pipeline:
 _target_: ProcessData.data_pipeline.PandasDataPipeline
 steps: 
  -
   _target_: ProcessData.data_cleaning.shift_close
   _partial_: true
  - 
    _target_: ProcessData.data_cleaning.create_label
    _partial_: true
  - 
    _target_: ProcessData.data_cleaning.drop_empty_window
    _partial_: true



Data_Source: './data/Unprocessed_Data.csv'   
  
model:
  model_params:
    learning_rate: 10
    max_depth: 5
    min_samples_leaf: 10
    max_leaf_nodes: 66
    l2_regularization: 1
    max_bins: 25
    max_iter: 5
    random_state: 42
    class_weight: "balanced"
  feature_depth: 49


